spring:
  application:
    name: MySmartKitchen

  datasource:
    url: jdbc:postgresql://localhost:5432/MySmartKitchen
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  flyway:
    enabled: false


  
  
  
  
  

